<?php
namespace app\facade;
use think\Facade;

class Test extends Facade
{
    protected static function getFacadeClass()
    {
        //parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return 'app\common\Test';
    }
}